CREATE TABLE booking (
    booking_id            INT AUTO_INCREMENT,
    booking_date          DATE NOT NULL,
    time_slot             ENUM('9:00AM-1:00PM', '1:00PM-5:00PM', '5:00PM-8:00PM') NOT NULL,
    cleaning_plan         ENUM('Weekly Cleaning', 'Fortnightly Cleaning', 'Monthly Cleaning', 'One-time Cleaning'),
    service_type          ENUM('Daily Cleaning', 'Hourly Cleaning', 'Spring Cleaning', 'Bond Cleaning') NOT NULL,
    special_instructions  TEXT,
    hours_count           INT,           
    subtotal             DECIMAL(10, 2) NOT NULL,
    discount_amount      DECIMAL(10, 2) NOT NULL,
    final_price          DECIMAL(10, 2) NOT NULL,
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    booking_status       ENUM('submitted', 'scheduled', 'completed', 'cancelled') NOT NULL DEFAULT 'submitted',
    customer_id          INT NOT NULL,
    property_id          INT NOT NULL,
    discount_id          INT,
    payment_id           INT NOT NULL,
    is_deleted           BOOLEAN DEFAULT 0,
    updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (booking_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE,
    FOREIGN KEY (property_id) REFERENCES propertys(property_id) ON DELETE CASCADE,
    FOREIGN KEY (discount_id) REFERENCES discount(discount_id) ON DELETE CASCADE,
    FOREIGN KEY (payment_id)  REFERENCES payment(payment_id) ON DELETE CASCADE
);
